### ISSUE TITLE
Update README with info about client configuration.

### ISSUE THREAD

**Issue by palyuga** [liveperson/Auto-Merger#14]
Now README file contains only the info about server configuration process and doesn't describe what how responsibilities divided between client and server.

**Comment by tomer-ben-david** [comment]
added a section named: "Automerver client / server notations explained." if any more info is required i'll be happy to elaborate more.

**Comment by tomer-ben-david** [comment]
@palyuga  is it working out for you?

**Comment by palyuga** [comment]
@tomer-ben-david yeah, sounds pretty informative. will try on Monday and let you know!

**Comment by tomer-ben-david** [comment]
closed due to no interaction lately.
